generel_intro = """WISC-V er en kognitiv test. Kognition er et andet ord for tænkning og testen kan give et indblik i mental funktion indenfor en række områder, herunder det sproglige, det visuelt-rummelige, ræsonnering, arbejdshukommelsen og mental arbejdshastighed. WISC-testen undersøger disse områder på en struktureret og systematisk måde, og scores sammenlignes med børn på samme alder med samme biologiske køn. Testens resultater er et øjeblik-billede og afhænger derfor også af dagsformen, om man fx er meget træt, nervøs eller om man er motiveret for at deltage. Det er vigtigt at huske på, at en testen er forbundet med en vis unøjagtighed. Derfor er testens resultat både angivet i scores, men også med et 95% konfidensinterval (herefter forkortet 95%KI), der viser det område vi med større statistisk sikkerhed kan vurdere at scores ligger indenfor. Der angives også en "percentil", hvilket er udtryk for hvor en score ligger sammenlignet med en norm-gruppe af børn som har samme biologiske køn og alder. Hvis man scorer 15. percentil betyder det, at 15% af børnene i norm-gruppen scorede lavere, og 85% af børnene i norm-gruppen scorede højere."""

beskrivelse_af_indekser = """Testens resultat angives i en samlet score: "Hele Intelligens Kvotient" (forkortet: HIK). Herudover måler testen på 5 forskellige indekser: verbal forståelse, arbejdshukommelse, forarbejdningshastighed, visuospatial bearbejdning og ræsonnering.
Det verbale forståelsesindeks (VFI) måler evnen til at forstå og kommunikere tanker og ideer verbalt. Indekset for arbejdshukommelses (AHI) måler evnen til mentalt at holde flere bolde i luften. Forarbejdningshastighedsindekset (FHI) måler mental arbejdshastighed. Det visuospatiale indeks (VSI) måler evnen til rumlig bearbejdning og evnen til visuelt at forstå og opfatte forholdet mellem helheder og dele. Ræsonneringsindekset (RSI) måler evnen til at tænke logisk og abstrakt, udvikle nye tankemønstre, drage konklusioner og se mønstre/sammenhænge. Testens resultat er opsummeret nedenfor i tekst og efterfølgende i tabel."""

fortsat_intro_til_lav_begavelse = """En lav score på testen er ikke et udtryk for, at man ikke kan udvikle sig, men et udtryk for at man i den specifikke test-situation opnåede en bestemt score. Når scoren er retvisende for barnets niveau vil barnet oftest udvikle sig sammen med gennemsnittet - så barnets rå-score stiger samtidig med at gennemsnittet også stiger. Derfor ser man ofte, at børn bliver ved med at ligge i nærheden af det samme område ift. gennemsnittet, men det er vigtigt ikke at forveksle dette med fraværet af udvikling, eller manglende potentiale herfor. Med dette i tankerne er det dog vigtigt at støtte barnet i at finde værdier og mål, som relaterer sig til ting, som er indenfor barnets kontrol. Eksempelvist er flid, ærlighed, omtanke, nysgerrighed og mod alt sammen fuldkommen indenfor barnets kontrol, hvor antallet af løste opgaver fx kun delvist er indenfor barnets kontrol.
Det er desuden vigtigt at huske på, at et hvert forsøg på at hjælpe kan have nogle uforudsete bivirkninger. Fx er det almindeligt at opleve frustrationer i brug af computer til ordblindhed, fordi de røde streger konstant minder eleven om, at de har stavet forkert og har svært ved det. Ligeledes kan en computer være et komplekst værktøj, som eleven har svært ved at overskue at anvende. Disse ting kan bidrage til at give en elev en oplevelse af at deres ressourcer ikke rækker til det som forventes af dem. Således er det vigtigt at man løbende er nysgerrig og undersøgende overfor om ens hjælpsomme intentioner også har den positive effekt man ønsker, eller om man skal justere og eller erstatte indsatsen. Hvis der gøres en ekstraordinær indsats for at støtte en elev kan dette være forbundet med at eleven føler sig anderledes og udstillet. Derfor er det vigtigt at støttehensyn tager højde for dette og at støtte gives på en måde der ikke udstiller det ekstraordinære behov for støtte. I de situationer, hvor det ikke er muligt at ”skjule” støtten, skal den positive effekt af støtten opvejes med evt. negative konsekvenser. 
Nedenfor gennemgås mere specifikke hensyn jævnfør testresultatet i WISC-V testen. 
"""

fortsat_intro_til_høj_begavelse = """En høj score på testen er ikke nødvendigvis et udtryk for at barnet ikke kan have behov for støtte. Høj begavelse kan også være et særligt behov, da man tit vil have et behov for større faglige udfordringer, for at man også lærer at koncentrere sig/gøre sig umage. Høj begavelse kan også være forbundet med situationer, som stiller store krav til tålmodighed og koncentration, da man ofte vil skulle vente på at andre bliver færdige eller klar. Høj begavelse kan desuden også medføre høje forventninger fra omgivelserne, som det kan være svært for barnet at leve op til.
Med dette i tankerne er det vigtigt at støtte barnet i at finde værdier og mål, som relaterer sig til ting, som er indenfor barnets kontrol. 
Eksempelvist er flid, ærlighed, omtanke og mod alt sammen fuldkommen indenfor elevens kontrol, hvor antallet af løste opgaver og ens karakterer kun delvist er indenfor elevens kontrol - og et barn med høj begavelse også bør udfordres med et passende omfang af opgaver med en passende sværhedsgrad."""
 